'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,n=6)=>v==null?'—':Number(v).toFixed(n),pct=v=>v==null?'—':(v>0?'+':'')+fmt(v,3)+'%',clock=t=>!t||t.startsWith('0001')?'—':new Date(t).toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false});
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'});
let displayedToday=today();
function rolloverDate(value,previous,current){return value===previous?current:value}
function followDay(){const current=today();if(current===displayedToday)return;const previous=displayedToday;displayedToday=current;const next=rolloverDate($('date').value,previous,current);if(next!==$('date').value){$('date').value=next;history=[];lastMinute='';loadHistory()}}
let rows=[],selected=(new URLSearchParams(location.search).get('symbol')||localStorage.getItem('iopv-fund')||'513090.SH'),direction='buy',history=[],health={},lastMinute='',loadEpoch=0;
const management=location.pathname==='/manage';$('market').hidden=management;if(management)$('market').style.display='none';$('management').hidden=!management;$(management?'nav-manage':'nav-market').classList.add('active');$('date').value=today();
$('toggle-funds').hidden=management;
$('toggle-funds').onclick=()=>{const open=$('fund-sidebar').hidden;$('fund-sidebar').hidden=!open;$('market').classList.toggle('sidebar-collapsed',!open);$('toggle-funds').setAttribute('aria-expanded',String(open));$('toggle-funds').textContent=open?'☰ 收起标的':'☰ 展开标的';draw()};
function selectedRow(){return rows.find(r=>r.symbol===selected)}
const reasonText={SUSPENDED_COMPONENT:'含今日已确认停牌成分',SUSPENSION_STATUS_UNAVAILABLE:'停牌核实记录读取失败',QUOTE_MISSING:'缺少成分报价',STALE_COMPONENT_MARKS:'含陈旧成分价，仅供观察',FEED_STALE:'行情流已中断',MIDPOINT_MISSING:'当日中间价缺失',SETTLEMENT_FX_UNAVAILABLE:'预估结算汇率暂不可用',ETF_NOT_LIVE:'ETF 非实时交易报价',PCF_PENDING:'PCF 等待中',PCF_DATE_MISMATCH:'PCF 日期不符',NAV_STALE:'估值已过期',PAUSED:'计算已暂停'};
function renderList(){const q=$('search').value.trim().toLowerCase();$('funds').innerHTML=rows.filter(r=>(r.symbol+r.name).toLowerCase().includes(q)).map(r=>`<button class="fund ${r.symbol===selected?'active':''}" data-symbol="${esc(r.symbol)}"><span><strong>${esc(r.name)}</strong><small>${r.symbol}</small>${(r.suspended||[]).length?'<small class="suspension-badge">今日停牌影响</small>':(r.suspension_pending||[]).length?'<small class="suspension-badge">缺报价 · 原因待确认</small>':''}</span><span class="value ${(r.midpoint_premium_pct||0)>0?'positive':'negative'}">${pct(r.midpoint_premium_pct)}</span></button>`).join('');$('fund-count').textContent=rows.length;}
$('funds').onclick=e=>{const b=e.target.closest('[data-symbol]');if(!b)return;selected=b.dataset.symbol;localStorage.setItem('iopv-fund',selected);loadHistory();renderList();renderDetail()};$('search').oninput=renderList;
async function loadHistory(){const epoch=++loadEpoch;try{const r=await fetch(`/api/v1/minutes?symbol=${encodeURIComponent(selected)}&date=${$('date').value}`);if(!r.ok)throw Error('历史数据读取失败');const v=await r.json();if(epoch===loadEpoch){history=v;renderDetail();draw()}}catch(e){if(epoch===loadEpoch)$('quality').textContent=e.message}}
$('date').onchange=()=>{loadHistory();renderDetail()};for(const [id,delta]of [['previous',-1],['next',1]])$(id).onclick=()=>{const d=new Date($('date').value+'T12:00:00+08:00');d.setDate(d.getDate()+delta);$('date').value=d.toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'});loadHistory();renderDetail()};$('today').onclick=()=>{$('date').value=today();loadHistory();renderDetail()};for(const d of ['buy','sell'])$(d).onclick=()=>{direction=d;$('buy').classList.toggle('selected',d==='buy');$('sell').classList.toggle('selected',d==='sell');renderDetail();draw()};
function renderDetail(){renderLedger();const p=selectedRow();if(!p)return;$('fund-code').textContent=p.symbol;$('fund-name').textContent=p.name;$('pcf').textContent=p.components?`PCF ${p.trade_date} · ${p.components} 只成分 · 每篮 ${p.unit.toLocaleString()} 份 · 预估现金 ${fmt(p.cash,2)} 元`:'等待当日 PCF';
 const historical=$('date').value!==today();const shown=historical?history.at(-1):p;const v=shown||{};renderComponentIssues(v,historical);
 const reasons=(v.reasons||[]).map(x=>reasonText[x]||x);if(v.fx_status==='reference_only')reasons.push('结算模型仅供观察');if(v.fx_status==='closed_reference')reasons.push('结算汇率已冻结（收盘参考）');if((v.suspended||[]).length)reasons.push('停牌成分：'+v.suspended.join('、'));if((v.suspension_pending||[]).length)reasons.push('缺价待核实：'+v.suspension_pending.join('、'));if(v.fx_error)reasons.push('汇率源失效：'+(v.fx_error.includes('cfets_unavailable')?'上游 CFETS 抓取失败':v.fx_error.includes('stale/unhealthy')?'源报价过期或不健康':v.fx_error)+'；源报价 '+clock(v.fx_at)+'，快照 '+clock(v.fx_generated_at));if(historical)reasons.unshift('历史分钟档案');$('quality').hidden=reasons.length===0||health.quote_window_open===false;$('quality').className='quality '+(reasons.length?'warn':'');$('quality').textContent=reasons.length?reasons.join(' · '):`成分报价完整 · ${clock(v.calculated_at)} 计算 · 盘中预估结算`;
 $('evidence').innerHTML=[['后备行情',(v.fallback_components||[]).length?'新浪实时基本行情：'+v.fallback_components.join('、'):'无，使用内网行情'],['成分覆盖',`${v.priced??0} / ${v.components??0}`],['计算时间',clock(v.calculated_at)],['最早成分时间',clock(v.oldest_quote_at)],['汇率时间',clock(v.fx_at)],['结算模型',v.fx_model||'—'],['PCF 版本',(v.pcf_sha256||'—').slice(0,20)],['信号数据状态',v.eligible_for_signal?'数据门禁通过':'观察 / 暂不可用']].map(([k,x])=>`<dt>${esc(k)}</dt><dd>${esc(x)}</dd>`).join('');
 const bk=historical?null:p.book;const canPremium=bk&&p.etf_price!=null&&Date.now()-new Date(p.calculated_at)<15000&&Date.now()-new Date(bk.observed_at)<30000;let entries=[];if(bk){for(let i=4;i>=0;i--)entries.push(['卖'+(i+1),bk.asks[i]]);for(let i=0;i<5;i++)entries.push(['买'+(i+1),bk.bids[i]])}const pr=(price,nav)=>canPremium&&price>0&&nav>0?pct((price/nav-1)*100):'—';const apiLevels=historical?[]:(p.book_premiums||[]).slice().sort((a,b)=>a.side!==b.side?(a.side==='ask'?-1:1):(a.side==='ask'?b.level-a.level:a.level-b.level));$('book').innerHTML=apiLevels.length?apiLevels.map(l=>`<tr class="${l.level===1?'best-level':''}"><td>${l.side==='ask'?'卖':'买'}${l.level}</td><td>${fmt(l.price,3)}</td><td>${l.volume==null?'—':String(Number((l.volume/100).toFixed(2)))}</td><td>${pct(l.midpoint_premium_pct)}</td><td>${pct(l[`settlement_${direction}_premium_pct`])}</td></tr>`).join(''):'<tr><td colspan="5">暂无实时五档报价</td></tr>';$('booktime').textContent=bk?clock(bk.observed_at):'';
}
function isChartMinute(m){return typeof m==='string'&&((m>='09:30'&&m<='12:00')||(m>='13:00'&&m<='16:08'))}
function chartData(){let list=history.filter(x=>isChartMinute(x.minute));const p=selectedRow();if(p&&p.trade_date===$('date').value&&p.calculated_at&&isChartMinute(p.minute)){const i=list.findIndex(x=>x.minute===p.minute);if(i>=0)list[i]=p;else list.push(p)}return list.sort((a,b)=>a.minute.localeCompare(b.minute))}
function minutes(s){const [h,m]=s.split(':').map(Number);return h*60+m}function axis(m){return m-570-(m>=780?60:0)}
let hover=null,chartMode='valuation';
const seriesVisible={mid:true,settlement:true,etf:true};
for(const b of document.querySelectorAll('[data-series]'))b.onclick=()=>{const key=b.dataset.series;seriesVisible[key]=!seriesVisible[key];b.setAttribute('aria-pressed',String(seriesVisible[key]));draw()};
function plot(id,data,series,isPct){const canvas=$(id),width=canvas.clientWidth,height=canvas.clientHeight,dpr=devicePixelRatio||1;canvas.width=width*dpr;canvas.height=height*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);const left=64,right=14,top=25,bottom=29,W=width-left-right,H=height-top-bottom;let vals=data.flatMap(p=>series.map(s=>p[s.key])).filter(x=>x!=null&&Number.isFinite(x));let lo=vals.length?Math.min(...vals):0,hi=vals.length?Math.max(...vals):1;if(isPct){lo=Math.min(lo,0);hi=Math.max(hi,0)}const pad=Math.max((hi-lo)*.15,isPct?.05:.0001);lo-=pad;hi+=pad;const X=m=>left+axis(m)/338*W,Y=v=>top+(hi-v)/(hi-lo)*H;
 c.fillStyle='#f0f4f9';c.fillRect(X(690),top,X(720)-X(690),H);c.fillStyle='#faf7ef';c.fillRect(X(900),top,X(968)-X(900),H);c.font='12px -apple-system, sans-serif';c.strokeStyle='#e3e9f2';c.lineWidth=1;c.fillStyle='#73839a';c.textAlign='right';for(let i=0;i<=4;i++){const y=top+i*H/4,v=hi-(hi-lo)*i/4;c.beginPath();c.moveTo(left,y);c.lineTo(width-right,y);c.stroke();c.fillText(v.toFixed(isPct?2:4)+(isPct?'%':''),left-8,y+4)}
 if(isPct){const zeroY=Y(0);c.save();c.strokeStyle='#526581';c.lineWidth=1.6;c.setLineDash([6,4]);c.beginPath();c.moveTo(left,zeroY);c.lineTo(width-right,zeroY);c.stroke();c.setLineDash([]);c.font='bold 12px -apple-system,sans-serif';c.fillStyle='#fff';c.fillRect(left-49,zeroY-9,44,18);c.fillStyle='#35465e';c.textAlign='right';c.fillText('0%',left-8,zeroY+4);c.restore()}
 c.textAlign='center';for(const [m,label]of [[570,'09:30'],[630,'10:30'],[690,'11:30'],[780,'12:00 / 13:00'],[840,'14:00'],[900,'15:00'],[968,'16:08']].filter(([m])=>width>=480||[570,780,900,968].includes(m))){c.fillText(label,X(m),height-7)}c.setLineDash([4,4]);c.strokeStyle='#a1b2c8';c.beginPath();c.moveTo(X(900),top);c.lineTo(X(900),top+H);c.stroke();c.setLineDash([]);if(!isPct){c.fillText('A股午休',X(705),13);c.fillText('A股收盘后',X(934),13)}
 for(const s of series){c.strokeStyle=s.color;c.lineWidth=2;c.beginPath();let prev=null;for(const p of data){const m=minutes(p.minute),v=p[s.key];if(v==null||m<570||m>968||(m>720&&m<780)){prev=null;continue}const x=X(m),y=Y(v);if(prev!=null&&(m-prev===1||(prev===720&&m===780)))c.lineTo(x,y);else c.moveTo(x,y);prev=m}c.stroke();const last=[...data].reverse().find(p=>p[s.key]!=null);if(last){c.fillStyle=s.color;c.beginPath();c.arc(X(minutes(last.minute)),Y(last[s.key]),3,0,Math.PI*2);c.fill()}}
 if(!vals.length&&series.length){c.fillStyle='#8a99aa';c.font='14px -apple-system,sans-serif';c.fillText('暂无该时段记录 · 服务从启动后逐分钟采集',width/2,height/2)}
 if(hover!=null){c.strokeStyle='#a1b2c8';c.setLineDash([3,3]);c.beginPath();c.moveTo(X(hover),top);c.lineTo(X(hover),top+H);c.stroke()};canvas._geometry={left,W,X};}
function chartSeries(mode,direction){return mode==='premium'?[{id:'mid',key:'midpoint_premium_pct',color:'#bd8700'},{id:'settlement',key:`settlement_${direction}_premium_pct`,color:'#008777'}]:[{id:'mid',key:'midpoint_iopv',color:'#bd8700'},{id:'settlement',key:`settlement_${direction}_iopv`,color:'#008777'},{id:'etf',key:'etf_price',color:'#2963ed'}]}
$('chart-mode').onclick=()=>{chartMode=chartMode==='valuation'?'premium':'valuation';hover=null;$('tooltip').style.display='none';draw()};
function draw(){const isPct=chartMode==='premium';$('chart-title').textContent=isPct?'分时溢价率':'分时估值';$('chart-mode').textContent=isPct?'切换分时估值图':'切换溢价率图';$('chart-mode').setAttribute('aria-pressed',String(isPct));$('navchart').setAttribute('aria-label',isPct?'09:30至16:08分时溢价率图':'09:30至16:08三线分时估值图');for(const b of document.querySelectorAll('[data-series]')){const k=b.dataset.series;b.hidden=isPct&&k==='etf';const label=k==='mid'?(isPct?'中间价溢价率':'中间价 IOPV'):k==='settlement'?(isPct?'预估结算溢价率':'预估结算 IOPV'):'ETF 实价';b.lastChild.textContent=label}plot('navchart',chartData(),chartSeries(chartMode,direction).filter(s=>seriesVisible[s.id]),isPct)}
$('navchart').onmousemove=e=>{const data=chartData(),g=$('navchart')._geometry;if(!g||!data.length)return;const x=e.offsetX;const p=data.reduce((a,b)=>Math.abs(g.X(minutes(a.minute))-x)<Math.abs(g.X(minutes(b.minute))-x)?a:b);hover=minutes(p.minute);draw();$('tooltip').innerHTML=`<b>${esc(p.trade_date)} ${p.minute}</b>${p.mode==='historical_reconstruction'?' · 历史重算':''}<br>中间价 IOPV　${fmt(p.midpoint_iopv,4)}<br>预估结算 IOPV　${fmt(p[`settlement_${direction}_iopv`],4)}<br>ETF 实价　${fmt(p.etf_price,3)}<br>溢价　${pct(p.midpoint_premium_pct)} / ${pct(p[`settlement_${direction}_premium_pct`])}`;$('tooltip').style.display='block';$('tooltip').style.left=Math.max(0,Math.min(x+15,$('navchart').clientWidth-300))+'px';$('tooltip').style.top='30px'};$('navchart').onmouseleave=()=>{hover=null;$('tooltip').style.display='none';draw()};window.addEventListener('resize',()=>{if(!management)draw()});
function renderManagement(){const labels=[['当日PCF',`${health.pcf_ready||0} / ${health.candidates||120}`,'基金清单'],['报价覆盖',`${health.quote_count||0} / ${health.subscriptions||0}`,'去重后的ETF与成分'],['接收帧数',(health.frames||0).toLocaleString(),'C++ TGW 实时接收'],['已落盘分钟行',(health.written_rows||0).toLocaleString(),'本次运行写入']];$('healthcards').innerHTML=labels.map(([k,v,n])=>`<article><label>${k}</label><strong>${v}</strong><small>${n}</small></article>`).join('');$('healthdetails').innerHTML=[['行情订阅时段',health.subscription_schedule||'—'],['当前订阅数',health.active_subscriptions??'—'],['汇率轮询',health.fx_polling?'时段内采集':'时段外暂停'],['当前数据日',health.active_date],['PCF 定时','工作日 08:40（北京时间）'],['上次 PCF 拉取',clock(health.pcf_last_attempt)],['下次 PCF 拉取',health.pcf_next_attempt?new Date(health.pcf_next_attempt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'—'],['行情状态',health.feed_state],['行情来源',health.shared_l1?'五合一共享 L1':'独立 TGW'],['监控信号口径',({midpoint:'中间价',settlement_buy:'买入港股结算',settlement_sell:'卖出港股结算'})[health.signal_basis]||'独立模块'],['最近行情',clock(health.feed_at)],['最近落盘',clock(health.last_write_at)],['计算状态',health.paused?'已暂停':'运行中，3秒/组'],['组内成分数',(health.group_loads||[]).join(' / ')],['源会话',health.session],['拒绝的帧',health.rejected_frames],['计算序号',health.sequence],['服务启动',clock(health.started_at)]].map(([k,v])=>`<dt>${k}</dt><dd>${esc(v)}</dd>`).join('');const errs=Object.entries(health.errors||{});$('errors').innerHTML=errs.length?errs.map(([k,v])=>`<p><b>${esc(k)}</b><br>${esc(v)}</p>`).join(''):'<p>当前未记录采集或存储错误。</p>';$('coverage').innerHTML=rows.map(p=>`<tr><td><a href="/?symbol=${p.symbol}">${p.symbol}</a></td><td>${esc(p.name)}</td><td>${p.priced||0} / ${p.components||0}</td><td>${p.midpoint_iopv==null?'未就绪':(p.stale||[]).length?'陈旧价格估值':'有估值'}</td><td>${esc([...(p.missing||[]),...(p.stale||[])].join(', '))}</td></tr>`).join('')}
for(const b of document.querySelectorAll('[data-action]'))b.onclick=async()=>{b.disabled=true;try{const r=await fetch('/api/v1/manage/'+b.dataset.action,{method:'POST',headers:{'X-IOPV-Manage':'1'}});$('manage-message').textContent=r.ok?'操作已接受':'操作未执行：管理操作需从本机页面发起'}finally{b.disabled=false}};
const urlSymbol=new URLSearchParams(location.search).get('symbol');if(urlSymbol)selected=urlSymbol;const stream=new EventSource('/api/v1/stream');stream.onmessage=e=>{const msg=JSON.parse(e.data);followDay();rows=msg.snapshots;health=msg.health;const fresh=Date.now()-new Date(health.feed_at)<30000;$('connection').textContent=(health.quote_window_open===false?'○ 休市驻留':fresh?'● 实时数据流':'◌ 等待 / 数据流陈旧')+' · '+clock(health.now);if(management)renderManagement();else{renderList();renderDetail();draw();const minute=clock(health.now).slice(0,5);if(minute!==lastMinute){lastMinute=minute;loadHistory()}}};stream.onerror=()=>{$('connection').textContent='连接中断，自动重连中'};loadHistory();

async function loadSuspensions(){if(!management)return;try{const r=await fetch('/api/v1/suspensions');if(!r.ok)throw Error('停牌核实读取失败');const items=await r.json();const confirmed=items.filter(x=>x.status==='suspended');const pending=items.filter(x=>x.status==='pending');$('suspension-summary').textContent=`${today()} · 已确认 ${confirmed.length} 只 / 涉及 ${new Set(confirmed.flatMap(x=>x.funds.map(f=>f.symbol))).size} 只基金 · 待确认 ${pending.length} 只`;$('suspension-rows').innerHTML=items.map(x=>`<tr><td>${esc(x.symbol)}</td><td>${{suspended:'今日已确认停牌',trading:'已核实非停牌，排查行情',pending:'缺报价，待核实'}[x.status]}</td><td>${x.funds.map(f=>`<a href="/?symbol=${esc(f.symbol)}">${esc(f.name)} (${esc(f.symbol)})</a>`).join('、')}</td><td>${esc(x.note)}<br>${clock(x.confirmed_at)}<br><button data-security="${esc(x.symbol)}" data-status="suspended">确认今日停牌</button> <button data-security="${esc(x.symbol)}" data-status="trading">确认非停牌 / 复牌</button></td></tr>`).join('')||'<tr><td colspan="4">目前没有缺价或已确认停牌的成分券。</td></tr>'}catch(e){$('suspension-summary').textContent=e.message}}
$('suspension-rows').onclick=async e=>{const b=e.target.closest('[data-security]');if(!b)return;const note=prompt('请输入今日核实依据（公告链接或人工核实说明）：');if(!note||!note.trim())return;b.disabled=true;try{const r=await fetch('/api/v1/manage/suspension',{method:'POST',headers:{'Content-Type':'application/json','X-IOPV-Manage':'1'},body:JSON.stringify({symbol:b.dataset.security,status:b.dataset.status,trade_date:today(),note:note.trim()})});$('manage-message').textContent=r.ok?'今日核实已保存；基金标记将在下一计算节拍更新':'保存失败，请在本机管理页操作';await loadSuspensions()}finally{b.disabled=false}};
loadSuspensions();setInterval(loadSuspensions,15000);

let ledger=null,ledgerRendered='';
function renderLedger(){if(!ledger||ledgerRendered===selected)return;ledgerRendered=selected;const r=ledger.records[selected];if(!r){$('ledger-content').textContent='现有台账未找到该标的，待补充验收。';return}
const groups=[['补券与轧差',[['申购补券时点','creation_buy_deadline'],['赎回代卖时点','redemption_sell_deadline'],['申购 RTGS','rtgs_subscription'],['管理人同日申赎轧差','same_day_netting_manager'],['轧差依据','same_day_netting_evidence']]],['申购交收',[['现金替代结算方式','subscription_cash_substitution_mode'],['现金替代交收时点','subscription_cash_substitution_settlement_time'],['份额交收时点','subscription_fund_units_settlement_time'],['份额可用时点','subscription_fund_units_available_time'],['现金替代退补款','subscription_cash_substitution_refund_time']]],['赎回交收',[['份额交收时点','redemption_fund_units_settlement_time'],['现金替代结算方式','redemption_cash_substitution_mode'],['现金替代款到账时限','redemption_cash_substitution_arrival_time']]],['现金差额',[['公告时点','cash_difference_announcement_time'],['清算时点','cash_difference_clearing_time'],['交收时点','cash_difference_settlement_time']]]];
groups.push(...[["基金特定轧差约定", [["轧差原文", "same_day_netting_basis"]]], ["收盘基金净值", [["净值计算时点", "nav_calculation_time"], ["净值公告时点", "nav_announcement_time"], ["证券估值价格口径", "nav_price_basis"], ["净值精度", "nav_precision"], ["正常港币估值汇率口径", "nav_fx_normal_method"], ["估值汇率来源", "nav_fx_source"], ["汇率取价时点", "nav_fx_reference_time"], ["币种与折算方向", "nav_fx_currency_scope"], ["备用汇率机制", "nav_fx_fallback"]]], ["申购补券汇率", [["成本与退补款规则", "creation_replacement_fx_rule"], ["实际结算汇率来源", "creation_replacement_fx_source"], ["汇率取价时点", "creation_replacement_fx_reference_time"], ["币种与折算方向", "creation_replacement_fx_currency"]]], ["赎回代卖汇率", [["卖出与替代金额规则", "redemption_replacement_fx_rule"], ["实际结算汇率来源", "redemption_replacement_fx_source"], ["汇率取价时点", "redemption_replacement_fx_reference_time"], ["币种与折算方向", "redemption_replacement_fx_currency"]]], ["现金替代费用", [["交易费用计入方式", "cash_substitution_fee_rule"]]], ["招募书 IOPV 口径", [["IOPV 计算公式", "iopv_formula"], ["证券价格口径", "iopv_price_basis"], ["盘中汇率来源", "iopv_fx_source"], ["汇率取价时点", "iopv_fx_reference_time"], ["计算与发布机构", "iopv_publisher"], ["发布频率与精度", "iopv_frequency_precision"]]]]);
const label=v=>({fund_document:'基金招募说明书',fund_specific_explicit:'基金文件明确约定',updated:'更新招募说明书'})[v]||v||'未记录';
let html=`<p class="muted">${esc(r.fund_name)} · 招募书 ${esc(r.latest_updated_prospectus_date||r.latest_prospectus_any_date||'未记录')} · 台账 PCF 基准日 ${esc(r.pcf_asof||'未记录')}</p><div class="ledger-grid">`;
const fieldValue=v=>{const text=String(label(v));return text.length>240?`<details class="ledger-clause"><summary>${esc(text.slice(0,100))}…（展开全文）</summary><p>${esc(text)}</p></details>`:esc(text)};
for(const [title,fields]of groups)html+=`<div><h3>${title}</h3><dl>${fields.map(([name,key])=>`<dt>${name}</dt><dd>${fieldValue(r[key])}</dd>`).join('')}</dl></div>`;
html+='</div>';
if(r.open_question)html+=`<div class="quality warn"><b>待确认事项</b><br>${esc(r.open_question)}</div>`;

try{const url=new URL(r.evidence_url);if(url.protocol==='https:')html+=`<p><a href="${esc(url.href)}" target="_blank" rel="noopener noreferrer">查看台账来源公告 ↗</a></p>`}catch{}
html+=`<p class="muted">台账快照：${esc(ledger.source_name)} · 导入 ${esc(ledger.imported_at.slice(0,10))}。PASS 表示该项已有依据；PENDING 表示待确认，不代表否定结论。</p>`;
$('ledger-content').innerHTML=html;
}
fetch('/ledger.json').then(r=>{if(!r.ok)throw Error('台账读取失败');return r.json()}).then(v=>{ledger=v;renderLedger()}).catch(()=>{$('ledger-content').textContent='验收台账暂不可用，请刷新重试。'});

let thresholdRevision=0;
async function loadThresholds(){if(!management)return;try{const r=await fetch('/api/v1/signal-settings');if(!r.ok)throw Error('阈值读取失败');const v=await r.json();thresholdRevision=v.revision;for(const k of ['radar','pull','premium'])$(k+'-threshold').value=v[k+'_pct']}catch(e){$('threshold-result').textContent=e.message}}
$('signal-settings').onsubmit=async e=>{e.preventDefault();try{const v={revision:thresholdRevision};for(const k of ['radar','pull','premium'])v[k+'_pct']=Number($(k+'-threshold').value);const r=await fetch('/api/v1/manage/signal-settings',{method:'POST',headers:{'Content-Type':'application/json','X-IOPV-Manage':'1'},body:JSON.stringify(v)});$('threshold-result').textContent=r.ok?'已保存，下一节拍生效':r.status===409?'设置已被修改，请刷新后再保存':'保存失败，请在 A 主机管理页操作';if(r.ok)await loadThresholds()}catch(e){$('threshold-result').textContent='保存失败：'+e.message}};loadThresholds();

function renderComponentIssues(v,historical){
 const issues=v.component_issues||[...new Set([...(v.missing||[]),...(v.stale||[]),...(v.suspended||[])])].map(symbol=>({symbol,quote_status:(v.missing||[]).includes(symbol)?'missing':(v.stale||[]).includes(symbol)?'stale':'available',suspension_status:(v.suspended||[]).includes(symbol)?'suspended':''}));
 $('component-issues-time').textContent=(historical?'历史快照 · ':'')+(v.trade_date||$('date').value)+' '+clock(v.calculated_at);
 $('component-issues').innerHTML=issues.length?issues.map(c=>{const quote={missing:'缺少有效报价',stale:'报价已过期',available:'已有报价'}[c.quote_status]||'待核实';const status={suspended:'已确认停牌',trading:'已核实非停牌'}[c.suspension_status]||'原因待确认（不等于停牌）';const link=/^\d{5}\.HK$/.test(c.symbol)?`<a href="https://stock.finance.sina.com.cn/hkstock/quotes/${c.symbol.slice(0,5)}.html" target="_blank" rel="noopener noreferrer">查看新浪行情 ↗</a>`:'';return `<tr><td>${esc(c.symbol)}</td><td>${esc(c.name||'未记录')}</td><td>${esc(quote)}</td><td>${esc(status)}</td><td>${clock(c.observed_at)}<br>${esc(({internal_l1:'内网行情',sina_rt_hk:'新浪后备'})[c.source]||'')}</td><td>${esc(c.note||'')} ${link}</td></tr>`}).join(''):`<tr><td colspan="6">${!v.calculated_at?'等待估值数据':(v.reasons||[]).some(x=>x==='PCF_PENDING'||x==='PCF_DATE_MISMATCH')?'PCF 未就绪，暂无法判断成分缺价':'该快照无缺价、过期报价或已确认停牌成分'}</td></tr>`;
}
