'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,n=6)=>v==null?'—':Number(v).toFixed(n),pct=v=>v==null?'—':(v>0?'+':'')+fmt(v,3)+'%',clock=t=>!t||t.startsWith('0001')?'—':new Date(t).toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false});
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'});
let rows=[],selected=localStorage.getItem('iopv-fund')||'513090.SH',direction='buy',history=[],health={},lastMinute='',loadEpoch=0;
const management=location.pathname==='/manage';$('market').hidden=management;if(management)$('market').style.display='none';$('management').hidden=!management;$(management?'nav-manage':'nav-market').classList.add('active');$('date').value=today();
function selectedRow(){return rows.find(r=>r.symbol===selected)}
const reasonText={SUSPENDED_COMPONENT:'含今日已确认停牌成分',SUSPENSION_STATUS_UNAVAILABLE:'停牌核实记录读取失败',QUOTE_MISSING:'缺少成分报价',STALE_COMPONENT_MARKS:'含陈旧成分价，仅供观察',FEED_STALE:'行情流已中断',MIDPOINT_MISSING:'当日中间价缺失',SETTLEMENT_FX_UNAVAILABLE:'预估结算汇率暂不可用',ETF_NOT_LIVE:'ETF 非实时交易报价',PCF_PENDING:'PCF 等待中',PCF_DATE_MISMATCH:'PCF 日期不符',NAV_STALE:'估值已过期',PAUSED:'计算已暂停'};
function renderList(){const q=$('search').value.trim().toLowerCase();$('funds').innerHTML=rows.filter(r=>(r.symbol+r.name).toLowerCase().includes(q)).map(r=>`<button class="fund ${r.symbol===selected?'active':''}" data-symbol="${esc(r.symbol)}"><span><strong>${esc(r.name)}</strong><small>${r.symbol}</small>${(r.suspended||[]).length?'<small class="suspension-badge">今日停牌影响</small>':(r.suspension_pending||[]).length?'<small class="suspension-badge">缺报价 · 停牌待确认</small>':''}</span><span class="value ${(r.midpoint_premium_pct||0)>0?'positive':'negative'}">${pct(r.midpoint_premium_pct)}</span></button>`).join('');$('fund-count').textContent=rows.length;}
$('funds').onclick=e=>{const b=e.target.closest('[data-symbol]');if(!b)return;selected=b.dataset.symbol;localStorage.setItem('iopv-fund',selected);loadHistory();renderList();renderDetail()};$('search').oninput=renderList;
async function loadHistory(){const epoch=++loadEpoch;try{const r=await fetch(`/api/v1/minutes?symbol=${encodeURIComponent(selected)}&date=${$('date').value}`);if(!r.ok)throw Error('历史数据读取失败');const v=await r.json();if(epoch===loadEpoch){history=v;draw()}}catch(e){if(epoch===loadEpoch)$('quality').textContent=e.message}}
$('date').onchange=()=>{loadHistory();renderDetail()};for(const [id,delta]of [['previous',-1],['next',1]])$(id).onclick=()=>{const d=new Date($('date').value+'T12:00:00+08:00');d.setDate(d.getDate()+delta);$('date').value=d.toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'});loadHistory();renderDetail()};$('today').onclick=()=>{$('date').value=today();loadHistory();renderDetail()};for(const d of ['buy','sell'])$(d).onclick=()=>{direction=d;$('buy').classList.toggle('selected',d==='buy');$('sell').classList.toggle('selected',d==='sell');renderDetail();draw()};
function renderDetail(){const p=selectedRow();if(!p)return;$('fund-code').textContent=p.symbol;$('fund-name').textContent=p.name;$('pcf').textContent=p.components?`PCF ${p.trade_date} · ${p.components} 只成分 · 每篮 ${p.unit.toLocaleString()} 份 · 预估现金 ${fmt(p.cash,2)} 元`:'等待当日 PCF';$('channel').textContent=(p.channel==='shenzhen'?'深圳':'上海')+'港股通 · '+(direction==='buy'?'买入港股使用预测卖出结算汇率':'卖出港股使用预测买入结算汇率');
 const historical=$('date').value!==today();const shown=historical?history.at(-1):p;const v=shown||{};$('mid').textContent=fmt(v.midpoint_iopv);$('settlement').textContent=fmt(v[`settlement_${direction}_iopv`]);$('etf').textContent=fmt(v.etf_price,4);$('premiums').textContent=pct(v.midpoint_premium_pct)+' / '+pct(v[`settlement_${direction}_premium_pct`]);$('midfx').textContent='中间价 '+fmt(v.midpoint_fx,5);$('settlefx').textContent='预估结算 '+fmt(v[`settlement_${direction}_fx`],8);$('etftime').textContent=clock(v.etf_quote_at)+(historical?' · 历史记录':'');
 const reasons=(v.reasons||[]).map(x=>reasonText[x]||x);if(v.fx_status==='reference_only')reasons.push('结算模型仅供观察');if(v.fx_status==='closed_reference')reasons.push('结算汇率已冻结（收盘参考）');if((v.suspended||[]).length)reasons.push('停牌成分：'+v.suspended.join('、'));if((v.suspension_pending||[]).length)reasons.push('停牌待核实：'+v.suspension_pending.join('、'));if(v.fx_error)reasons.push('汇率源失效：'+(v.fx_error.includes('cfets_unavailable')?'上游 CFETS 抓取失败':v.fx_error.includes('stale/unhealthy')?'源报价过期或不健康':v.fx_error)+'；源报价 '+clock(v.fx_at)+'，快照 '+clock(v.fx_generated_at));if(historical)reasons.unshift('历史分钟档案');$('quality').className='quality '+(reasons.length?'warn':'');$('quality').textContent=reasons.length?reasons.join(' · '):`成分报价完整 · ${clock(v.calculated_at)} 计算 · 盘中预估结算`;
 $('evidence').innerHTML=[['成分覆盖',`${v.priced??0} / ${v.components??0}`],['计算时间',clock(v.calculated_at)],['最早成分时间',clock(v.oldest_quote_at)],['汇率时间',clock(v.fx_at)],['结算模型',v.fx_model||'—'],['PCF 版本',(v.pcf_sha256||'—').slice(0,20)],['信号数据状态',v.eligible_for_signal?'数据门禁通过':'观察 / 暂不可用']].map(([k,x])=>`<dt>${esc(k)}</dt><dd>${esc(x)}</dd>`).join('');$('export').href=`/api/v1/export.csv?symbol=${encodeURIComponent(selected)}&date=${$('date').value}`;
 const bk=historical?null:p.book;const canPremium=bk&&p.etf_price!=null&&Date.now()-new Date(p.calculated_at)<15000&&Date.now()-new Date(bk.observed_at)<30000;let entries=[];if(bk){for(let i=4;i>=0;i--)entries.push(['卖'+(i+1),bk.asks[i]]);for(let i=0;i<5;i++)entries.push(['买'+(i+1),bk.bids[i]])}const pr=(price,nav)=>canPremium&&price>0&&nav>0?pct((price/nav-1)*100):'—';const apiLevels=historical?[]:(p.book_premiums||[]).slice().sort((a,b)=>a.side!==b.side?(a.side==='ask'?-1:1):(a.side==='ask'?b.level-a.level:a.level-b.level));$('book').innerHTML=apiLevels.length?apiLevels.map(l=>`<tr><td>${l.side==='ask'?'卖':'买'}${l.level}</td><td>${fmt(l.price,4)}</td><td>${fmt(l.volume,0)}</td><td>${pct(l.midpoint_premium_pct)}</td><td>${pct(l[`settlement_${direction}_premium_pct`])}</td></tr>`).join(''):'<tr><td colspan="5">暂无实时五档报价</td></tr>';$('booktime').textContent=bk?clock(bk.observed_at):'';
}
function chartData(){let list=history.slice();const p=selectedRow();if(p&&p.trade_date===$('date').value&&p.calculated_at&&p.minute>='09:30'&&p.minute<='16:08'){const i=list.findIndex(x=>x.minute===p.minute);if(i>=0)list[i]=p;else list.push(p)}return list.sort((a,b)=>a.minute.localeCompare(b.minute))}
function minutes(s){const [h,m]=s.split(':').map(Number);return h*60+m}function axis(m){return m-570-(m>=780?60:0)}
let hover=null;
function plot(id,data,series,isPct){const canvas=$(id),width=canvas.clientWidth,height=canvas.clientHeight,dpr=devicePixelRatio||1;canvas.width=width*dpr;canvas.height=height*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);const left=64,right=14,top=25,bottom=29,W=width-left-right,H=height-top-bottom;let vals=data.flatMap(p=>series.map(s=>p[s.key])).filter(x=>x!=null&&Number.isFinite(x));let lo=vals.length?Math.min(...vals):0,hi=vals.length?Math.max(...vals):1;if(isPct){lo=Math.min(lo,0);hi=Math.max(hi,0)}const pad=Math.max((hi-lo)*.15,isPct?.05:.0001);lo-=pad;hi+=pad;const X=m=>left+axis(m)/338*W,Y=v=>top+(hi-v)/(hi-lo)*H;
 c.fillStyle='#f0f4f9';c.fillRect(X(690),top,X(720)-X(690),H);c.fillStyle='#faf7ef';c.fillRect(X(900),top,X(968)-X(900),H);c.font='12px -apple-system, sans-serif';c.strokeStyle='#e3e9f2';c.lineWidth=1;c.fillStyle='#73839a';c.textAlign='right';for(let i=0;i<=4;i++){const y=top+i*H/4,v=hi-(hi-lo)*i/4;c.beginPath();c.moveTo(left,y);c.lineTo(width-right,y);c.stroke();c.fillText(v.toFixed(isPct?2:4)+(isPct?'%':''),left-8,y+4)}
 c.textAlign='center';for(const [m,label]of [[570,'09:30'],[630,'10:30'],[690,'11:30'],[780,'12:00 / 13:00'],[840,'14:00'],[900,'15:00'],[968,'16:08']]){c.fillText(label,X(m),height-7)}c.setLineDash([4,4]);c.strokeStyle='#a1b2c8';c.beginPath();c.moveTo(X(900),top);c.lineTo(X(900),top+H);c.stroke();c.setLineDash([]);if(!isPct){c.fillText('A股午休',X(705),13);c.fillText('A股收盘后',X(934),13)}
 for(const s of series){c.strokeStyle=s.color;c.lineWidth=2;c.beginPath();let prev=null;for(const p of data){const m=minutes(p.minute),v=p[s.key];if(v==null||m<570||m>968||(m>720&&m<780)){prev=null;continue}const x=X(m),y=Y(v);if(prev!=null&&(m-prev===1||(prev===720&&m===780)))c.lineTo(x,y);else c.moveTo(x,y);prev=m}c.stroke();const last=[...data].reverse().find(p=>p[s.key]!=null);if(last){c.fillStyle=s.color;c.beginPath();c.arc(X(minutes(last.minute)),Y(last[s.key]),3,0,Math.PI*2);c.fill()}}
 if(!vals.length){c.fillStyle='#8a99aa';c.font='14px -apple-system,sans-serif';c.fillText('暂无该时段记录 · 服务从启动后逐分钟采集',width/2,height/2)}
 if(hover!=null){c.strokeStyle='#a1b2c8';c.setLineDash([3,3]);c.beginPath();c.moveTo(X(hover),top);c.lineTo(X(hover),top+H);c.stroke()};canvas._geometry={left,W,X};}
function draw(){const data=chartData();plot('navchart',data,[{key:'midpoint_iopv',color:'#bd8700'},{key:`settlement_${direction}_iopv`,color:'#008777'},{key:'etf_price',color:'#2963ed'}],false);plot('premiumchart',data,[{key:'midpoint_premium_pct',color:'#bd8700'},{key:`settlement_${direction}_premium_pct`,color:'#008777'}],true);$('samples').textContent=`${history.length} 个落盘分钟`}
$('navchart').onmousemove=e=>{const data=chartData(),g=$('navchart')._geometry;if(!g||!data.length)return;const x=e.offsetX;const p=data.reduce((a,b)=>Math.abs(g.X(minutes(a.minute))-x)<Math.abs(g.X(minutes(b.minute))-x)?a:b);hover=minutes(p.minute);draw();$('tooltip').innerHTML=`<b>${esc(p.trade_date)} ${p.minute}</b><br>中间价 IOPV　${fmt(p.midpoint_iopv,8)}<br>预估结算 IOPV　${fmt(p[`settlement_${direction}_iopv`],8)}<br>ETF 实价　${fmt(p.etf_price,4)}<br>溢价　${pct(p.midpoint_premium_pct)} / ${pct(p[`settlement_${direction}_premium_pct`])}`;$('tooltip').style.display='block';$('tooltip').style.left=Math.max(0,Math.min(x+15,$('navchart').clientWidth-300))+'px';$('tooltip').style.top='30px'};$('navchart').onmouseleave=()=>{hover=null;$('tooltip').style.display='none';draw()};window.addEventListener('resize',()=>{if(!management)draw()});
function renderManagement(){const labels=[['当日PCF',`${health.pcf_ready||0} / ${health.candidates||120}`,'基金清单'],['报价覆盖',`${health.quote_count||0} / ${health.subscriptions||0}`,'去重后的ETF与成分'],['接收帧数',(health.frames||0).toLocaleString(),'C++ TGW 实时接收'],['已落盘分钟行',(health.written_rows||0).toLocaleString(),'本次运行写入']];$('healthcards').innerHTML=labels.map(([k,v,n])=>`<article><label>${k}</label><strong>${v}</strong><small>${n}</small></article>`).join('');$('healthdetails').innerHTML=[['行情状态',health.feed_state],['最近行情',clock(health.feed_at)],['最近落盘',clock(health.last_write_at)],['计算状态',health.paused?'已暂停':'运行中，3秒/组'],['组内成分数',(health.group_loads||[]).join(' / ')],['源会话',health.session],['拒绝的帧',health.rejected_frames],['计算序号',health.sequence],['服务启动',clock(health.started_at)]].map(([k,v])=>`<dt>${k}</dt><dd>${esc(v)}</dd>`).join('');const errs=Object.entries(health.errors||{});$('errors').innerHTML=errs.length?errs.map(([k,v])=>`<p><b>${esc(k)}</b><br>${esc(v)}</p>`).join(''):'<p>当前未记录采集或存储错误。</p>';$('coverage').innerHTML=rows.map(p=>`<tr><td><a href="/?symbol=${p.symbol}">${p.symbol}</a></td><td>${esc(p.name)}</td><td>${p.priced||0} / ${p.components||0}</td><td>${p.midpoint_iopv==null?'未就绪':(p.stale||[]).length?'陈旧价格估值':'有估值'}</td><td>${esc([...(p.missing||[]),...(p.stale||[])].join(', '))}</td></tr>`).join('')}
for(const b of document.querySelectorAll('[data-action]'))b.onclick=async()=>{b.disabled=true;try{const r=await fetch('/api/v1/manage/'+b.dataset.action,{method:'POST',headers:{'X-IOPV-Manage':'1'}});$('manage-message').textContent=r.ok?'操作已接受':'操作未执行：管理操作需从本机页面发起'}finally{b.disabled=false}};
const urlSymbol=new URLSearchParams(location.search).get('symbol');if(urlSymbol)selected=urlSymbol;const stream=new EventSource('/api/v1/stream');stream.onmessage=e=>{const msg=JSON.parse(e.data);rows=msg.snapshots;health=msg.health;const fresh=Date.now()-new Date(health.feed_at)<30000;$('connection').textContent=(fresh?'● 实时数据流':'◌ 等待 / 数据流陈旧')+' · '+clock(health.now);if(management)renderManagement();else{renderList();renderDetail();draw();const minute=clock(health.now).slice(0,5);if(minute!==lastMinute){lastMinute=minute;loadHistory()}}};stream.onerror=()=>{$('connection').textContent='连接中断，自动重连中'};loadHistory();

async function loadSuspensions(){if(!management)return;try{const r=await fetch('/api/v1/suspensions');if(!r.ok)throw Error('停牌核实读取失败');const items=await r.json();const confirmed=items.filter(x=>x.status==='suspended');const pending=items.filter(x=>x.status==='pending');$('suspension-summary').textContent=`${today()} · 已确认 ${confirmed.length} 只 / 涉及 ${new Set(confirmed.flatMap(x=>x.funds.map(f=>f.symbol))).size} 只基金 · 待确认 ${pending.length} 只`;$('suspension-rows').innerHTML=items.map(x=>`<tr><td>${esc(x.symbol)}</td><td>${{suspended:'今日已确认停牌',trading:'已核实非停牌，排查行情',pending:'缺报价，待核实'}[x.status]}</td><td>${x.funds.map(f=>`<a href="/?symbol=${esc(f.symbol)}">${esc(f.name)} (${esc(f.symbol)})</a>`).join('、')}</td><td>${esc(x.note)}<br>${clock(x.confirmed_at)}<br><button data-security="${esc(x.symbol)}" data-status="suspended">确认今日停牌</button> <button data-security="${esc(x.symbol)}" data-status="trading">确认非停牌 / 复牌</button></td></tr>`).join('')||'<tr><td colspan="4">目前没有缺价或已确认停牌的成分券。</td></tr>'}catch(e){$('suspension-summary').textContent=e.message}}
$('suspension-rows').onclick=async e=>{const b=e.target.closest('[data-security]');if(!b)return;const note=prompt('请输入今日核实依据（公告链接或人工核实说明）：');if(!note||!note.trim())return;b.disabled=true;try{const r=await fetch('/api/v1/manage/suspension',{method:'POST',headers:{'Content-Type':'application/json','X-IOPV-Manage':'1'},body:JSON.stringify({symbol:b.dataset.security,status:b.dataset.status,trade_date:today(),note:note.trim()})});$('manage-message').textContent=r.ok?'今日核实已保存；基金标记将在下一计算节拍更新':'保存失败，请在本机管理页操作';await loadSuspensions()}finally{b.disabled=false}};
loadSuspensions();setInterval(loadSuspensions,15000);
